# Generated by Django 4.2.2 on 2025-06-17 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "message_id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Сообщения",
                    ),
                ),
                (
                    "subject_letter",
                    models.CharField(
                        blank=True,
                        help_text="Введите тему",
                        max_length=100,
                        null=True,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "letter",
                    models.TextField(
                        blank=True,
                        help_text="Введите текст",
                        max_length=20000,
                        null=True,
                        verbose_name="Текст письма",
                    ),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество просмотров",
                        verbose_name="Счетчик просмотров",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите автора письма",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "письмо",
                "verbose_name_plural": "письма",
                "ordering": ["letter"],
                "permissions": [
                    ("can_edit_subject_letter", "Can edit subject_letter"),
                    ("can_edit_letter", "Can edit letter"),
                ],
            },
        ),
    ]
