# Generated by Django 4.2.2 on 2025-06-17 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "newsletter_id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Рассылки",
                    ),
                ),
                (
                    "first_shipment",
                    models.DateTimeField(
                        auto_now_add=True,
                        max_length=10,
                        verbose_name="Дата и время первой отправки",
                    ),
                ),
                (
                    "end_shipment",
                    models.DateTimeField(
                        editable=False,
                        max_length=10,
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                (
                    "status_news_letter",
                    models.CharField(
                        choices=[
                            ("Создана", "Создана"),
                            ("Запущена", "Запущена"),
                            ("Завершена", "Завершена"),
                        ],
                        default="Создана",
                        max_length=100,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        max_length=100,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="message.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="emails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "статус",
                "verbose_name_plural": "статусы",
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_attempt",
                    models.DateTimeField(
                        auto_now=True,
                        max_length=10,
                        verbose_name="Дата и время попытки отправки рассылки",
                    ),
                ),
                (
                    "status_mailing_attempt",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                        max_length=10,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "mail_server_response",
                    models.TextField(
                        max_length=200, verbose_name="Ответ почтового сервера"
                    ),
                ),
                (
                    "news_letter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sending.newsletter",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "статус",
                "verbose_name_plural": "статусы",
            },
        ),
    ]
