# Generated by Django 4.2.2 on 2025-06-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailingRecipient",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Пользователя",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Email_mailing_recipient",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Введите ваши инициалы",
                        max_length=150,
                        null=True,
                        verbose_name="Ф.И.О.",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Введите комментарии",
                        max_length=1000,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "message_id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Сообщения пользователя",
                    ),
                ),
                (
                    "subject_letter",
                    models.CharField(
                        blank=True,
                        help_text="Введите тему",
                        max_length=100,
                        null=True,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "letter",
                    models.TextField(
                        blank=True,
                        help_text="Введите текст",
                        max_length=300,
                        null=True,
                        verbose_name="Текст письма",
                    ),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество просмотров",
                        verbose_name="Счетчик просмотров",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите автора письма",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user",
                        to="sending.mailingrecipient",
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "письмо",
                "verbose_name_plural": "письма",
                "ordering": ["letter"],
                "permissions": [
                    ("can_edit_subject_letter", "Can edit subject_letter"),
                    ("can_edit_letter", "Can edit letter"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "newsletter_id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Рассылки",
                    ),
                ),
                (
                    "first_shipment",
                    models.DateTimeField(
                        auto_now_add=True,
                        max_length=10,
                        verbose_name="Дата и время первой отправки",
                    ),
                ),
                (
                    "end_shipment",
                    models.DateTimeField(
                        editable=False,
                        max_length=10,
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                (
                    "status_news_letter",
                    models.CharField(
                        choices=[
                            ("Создана", "Создана"),
                            ("Запущена", "Запущена"),
                            ("Завершена", "Завершена"),
                        ],
                        default="Создана",
                        max_length=100,
                        verbose_name="Статус",
                    ),
                ),
                ("disabling_mailings", models.BooleanField(default=False)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        max_length=100,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="sending.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="emails",
                        to="sending.mailingrecipient",
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "статус",
                "verbose_name_plural": "статусы",
                "ordering": ["disabling_mailings"],
                "permissions": [
                    ("can_edit_disabling_mailings", "Сan edit disabling mailings")
                ],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_attempt",
                    models.DateTimeField(
                        auto_now=True,
                        max_length=10,
                        verbose_name="Дата и время попытки отправки рассылки",
                    ),
                ),
                (
                    "status_mailing_attempt",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                        max_length=50,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "mail_server_response",
                    models.TextField(
                        max_length=200, verbose_name="Ответ почтового сервера"
                    ),
                ),
                (
                    "news_letter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletter",
                        to="sending.newsletter",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "статус",
                "verbose_name_plural": "статусы",
            },
        ),
    ]
