# Generated by Django 4.2.2 on 2025-06-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_blog", "0004_alter_blog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["blog_name"],
                "permissions": [
                    ("can_edit_blog_name", "Can edit blog_name"),
                    ("can_edit_description", "Can edit description"),
                    ("can_unpublish_blog", "Can unpublish blog"),
                ],
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
            },
        ),
    ]
