# Generated by Django 4.2.2 on 2025-05-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloguser",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Token"
            ),
        ),
    ]
