# Generated by Django 4.2.2 on 2025-06-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_users", "0002_bloguser_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloguser",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Введите имя пользователя",
                max_length=150,
                null=True,
                verbose_name="Имя пользователя",
            ),
        ),
    ]
